name: Push to Staging

on:
  push:
    branches: ["staging"]

jobs:
  build:
    runs-on: [self-hosted, staging]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Execute the Jar file
        run: sudo kill `sudo lsof -t -i:80` & sudo java -jar /home/ubuntu/backend/_work/java/java/target/cicddemo-0.0.1-SNAPSHOT.jar &
